// -------------------------------------------------------
// 📄 pdfTemplate.js — Ortak KUSTO PDF Şablonu
// -------------------------------------------------------
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

/**
 * Ortak KUSTO PDF Template
 * @param {Object} options { title, tableHead, tableBody, source }
 */
export function generateKustoPDF({ title, tableHead, tableBody, source }) {
  const doc = new jsPDF("p", "mm", "a4");
  const today = new Date().toLocaleDateString();

  // 🎨 Üst gri bant
  doc.setFillColor(240, 240, 240);
  doc.rect(0, 0, 210, 25, "F");

  // 🧠 Başlık
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("KUSTO Smart Construction System", 14, 16);

  // 📆 Tarih ve proje bilgisi
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text("Project: Diamond Premium Life", 150, 12);
  doc.text(`Date: ${today}`, 150, 18);

  // 📋 Rapor başlığı
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(title, 14, 35);

  // 🧾 Tablo
  autoTable(doc, {
    startY: 45,
    head: [tableHead],
    body: tableBody,
    theme: "grid",
    styles: {
      fontSize: 10,
      halign: "center",
      cellPadding: 3,
      lineColor: [80, 80, 80],
      lineWidth: 0.3,
    },
    headStyles: {
      fillColor: [66, 135, 245],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [245, 245, 245],
    },
  });

  // 📜 Alt bilgi
  const finalY = doc.lastAutoTable.finalY + 10;
  doc.line(14, finalY, 196, finalY);
  doc.setFontSize(9);
  doc.text(
    "Generated by Kusto Smart Construction Dashboard — © 2025",
    14,
    finalY + 6
  );
  doc.text(source, 14, finalY + 12);

  return doc;
}
